---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    ignore-errors: false
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: redmine
    image: buluma/docker-centos7-ansible:latest
    privileged: true
    capabilities:
      - SYS_ADMIN
    volume_mounts:
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ANSIBLE0013
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: true
  lint:
    name: flake8
    enabled: false
